import { z } from 'zod';
import type { Context } from '@deepseek-ai/cordis';
export declare const viewSchema: z.ZodObject<{
    version: z.ZodLiteral<1>;
    sessionId: z.ZodString;
    seq: z.ZodNumber;
    updatedAt: z.ZodNumber;
    totals: z.ZodObject<{
        calls: z.ZodNumber;
        reported: z.ZodNumber;
        exactTotals: z.ZodNumber;
        tokens: z.ZodNumber;
        input: z.ZodNumber;
        output: z.ZodNumber;
        cacheRead: z.ZodNumber;
        cacheWrite: z.ZodNumber;
        reasoning: z.ZodNumber;
        reasoningReports: z.ZodNumber;
        modelMs: z.ZodNumber;
        timedCalls: z.ZodNumber;
        firstMs: z.ZodNumber;
        firstSamples: z.ZodNumber;
        reasoningMs: z.ZodNumber;
        tools: z.ZodNumber;
        toolErrors: z.ZodNumber;
        toolMs: z.ZodNumber;
        bashMs: z.ZodOptional<z.ZodNumber>;
        retries: z.ZodNumber;
    }, z.core.$strip>;
    models: z.ZodArray<z.ZodObject<{
        calls: z.ZodNumber;
        reported: z.ZodNumber;
        exactTotals: z.ZodNumber;
        tokens: z.ZodNumber;
        input: z.ZodNumber;
        output: z.ZodNumber;
        cacheRead: z.ZodNumber;
        cacheWrite: z.ZodNumber;
        reasoning: z.ZodNumber;
        reasoningReports: z.ZodNumber;
        modelMs: z.ZodNumber;
        timedCalls: z.ZodNumber;
        firstMs: z.ZodNumber;
        firstSamples: z.ZodNumber;
        reasoningMs: z.ZodNumber;
        tools: z.ZodNumber;
        toolErrors: z.ZodNumber;
        toolMs: z.ZodNumber;
        bashMs: z.ZodOptional<z.ZodNumber>;
        retries: z.ZodNumber;
        provider: z.ZodString;
        model: z.ZodString;
        effort: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>>;
    turn: z.ZodNullable<z.ZodObject<{
        number: z.ZodNumber;
        startedAt: z.ZodNumber;
        endedAt: z.ZodNullable<z.ZodNumber>;
        steps: z.ZodNumber;
        stats: z.ZodObject<{
            calls: z.ZodNumber;
            reported: z.ZodNumber;
            exactTotals: z.ZodNumber;
            tokens: z.ZodNumber;
            input: z.ZodNumber;
            output: z.ZodNumber;
            cacheRead: z.ZodNumber;
            cacheWrite: z.ZodNumber;
            reasoning: z.ZodNumber;
            reasoningReports: z.ZodNumber;
            modelMs: z.ZodNumber;
            timedCalls: z.ZodNumber;
            firstMs: z.ZodNumber;
            firstSamples: z.ZodNumber;
            reasoningMs: z.ZodNumber;
            tools: z.ZodNumber;
            toolErrors: z.ZodNumber;
            toolMs: z.ZodNumber;
            bashMs: z.ZodOptional<z.ZodNumber>;
            retries: z.ZodNumber;
        }, z.core.$strip>;
        route: z.ZodOptional<z.ZodObject<{
            provider: z.ZodString;
            model: z.ZodString;
            effort: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    pending: z.ZodNullable<z.ZodObject<{
        turn: z.ZodNumber;
        step: z.ZodNumber;
        start: z.ZodNullable<z.ZodNumber>;
        reasoningFirst: z.ZodNullable<z.ZodNumber>;
        reasoningLast: z.ZodNullable<z.ZodNumber>;
        lastContentAt: z.ZodNullable<z.ZodNumber>;
    }, z.core.$strip>>;
    findings: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        kind: z.ZodString;
        turn: z.ZodNumber;
        seqs: z.ZodArray<z.ZodNumber>;
        steps: z.ZodArray<z.ZodNumber>;
        title: z.ZodString;
        detail: z.ZodString;
    }, z.core.$strip>>;
    findingCount: z.ZodNumber;
}, z.core.$strip>;
declare const stateSchema: z.ZodObject<{
    version: z.ZodLiteral<1>;
    sessionId: z.ZodString;
    skip: z.ZodNumber;
    seq: z.ZodNumber;
    updatedAt: z.ZodNumber;
    route: z.ZodObject<{
        provider: z.ZodString;
        model: z.ZodString;
        effort: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    }, z.core.$strip>;
    totals: z.ZodObject<{
        calls: z.ZodNumber;
        reported: z.ZodNumber;
        exactTotals: z.ZodNumber;
        tokens: z.ZodNumber;
        input: z.ZodNumber;
        output: z.ZodNumber;
        cacheRead: z.ZodNumber;
        cacheWrite: z.ZodNumber;
        reasoning: z.ZodNumber;
        reasoningReports: z.ZodNumber;
        modelMs: z.ZodNumber;
        timedCalls: z.ZodNumber;
        firstMs: z.ZodNumber;
        firstSamples: z.ZodNumber;
        reasoningMs: z.ZodNumber;
        tools: z.ZodNumber;
        toolErrors: z.ZodNumber;
        toolMs: z.ZodNumber;
        bashMs: z.ZodOptional<z.ZodNumber>;
        retries: z.ZodNumber;
    }, z.core.$strip>;
    models: z.ZodArray<z.ZodObject<{
        calls: z.ZodNumber;
        reported: z.ZodNumber;
        exactTotals: z.ZodNumber;
        tokens: z.ZodNumber;
        input: z.ZodNumber;
        output: z.ZodNumber;
        cacheRead: z.ZodNumber;
        cacheWrite: z.ZodNumber;
        reasoning: z.ZodNumber;
        reasoningReports: z.ZodNumber;
        modelMs: z.ZodNumber;
        timedCalls: z.ZodNumber;
        firstMs: z.ZodNumber;
        firstSamples: z.ZodNumber;
        reasoningMs: z.ZodNumber;
        tools: z.ZodNumber;
        toolErrors: z.ZodNumber;
        toolMs: z.ZodNumber;
        bashMs: z.ZodOptional<z.ZodNumber>;
        retries: z.ZodNumber;
        provider: z.ZodString;
        model: z.ZodString;
    }, z.core.$strip>>;
    turn: z.ZodNullable<z.ZodObject<{
        number: z.ZodNumber;
        startedAt: z.ZodNumber;
        endedAt: z.ZodNullable<z.ZodNumber>;
        steps: z.ZodNumber;
        stats: z.ZodObject<{
            calls: z.ZodNumber;
            reported: z.ZodNumber;
            exactTotals: z.ZodNumber;
            tokens: z.ZodNumber;
            input: z.ZodNumber;
            output: z.ZodNumber;
            cacheRead: z.ZodNumber;
            cacheWrite: z.ZodNumber;
            reasoning: z.ZodNumber;
            reasoningReports: z.ZodNumber;
            modelMs: z.ZodNumber;
            timedCalls: z.ZodNumber;
            firstMs: z.ZodNumber;
            firstSamples: z.ZodNumber;
            reasoningMs: z.ZodNumber;
            tools: z.ZodNumber;
            toolErrors: z.ZodNumber;
            toolMs: z.ZodNumber;
            bashMs: z.ZodOptional<z.ZodNumber>;
            retries: z.ZodNumber;
        }, z.core.$strip>;
        route: z.ZodOptional<z.ZodObject<{
            provider: z.ZodString;
            model: z.ZodString;
            effort: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    open: z.ZodNullable<z.ZodObject<{
        turn: z.ZodNumber;
        step: z.ZodNumber;
        start: z.ZodNullable<z.ZodNumber>;
        first: z.ZodNullable<z.ZodNumber>;
        reasoningFirst: z.ZodNullable<z.ZodNumber>;
        reasoningLast: z.ZodNullable<z.ZodNumber>;
        lastContentAt: z.ZodNullable<z.ZodNumber>;
        usage: z.ZodNullable<z.ZodObject<{
            input: z.ZodNumber;
            output: z.ZodNumber;
            cacheRead: z.ZodNumber;
            cacheWrite: z.ZodNumber;
            reasoning: z.ZodNullable<z.ZodNumber>;
            tokens: z.ZodNumber;
            exact: z.ZodBoolean;
        }, z.core.$strip>>;
        route: z.ZodObject<{
            provider: z.ZodString;
            model: z.ZodString;
            effort: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        }, z.core.$strip>;
    }, z.core.$strip>>;
    tools: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        start: z.ZodNumber;
        seq: z.ZodNumber;
        step: z.ZodNumber;
        route: z.ZodObject<{
            provider: z.ZodString;
            model: z.ZodString;
            effort: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        }, z.core.$strip>;
        signature: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>>;
    previousFailure: z.ZodNullable<z.ZodObject<{
        signature: z.ZodString;
        resultHash: z.ZodString;
        turn: z.ZodNumber;
        seqs: z.ZodArray<z.ZodNumber>;
        steps: z.ZodArray<z.ZodNumber>;
    }, z.core.$strip>>;
    findings: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        kind: z.ZodString;
        turn: z.ZodNumber;
        seqs: z.ZodArray<z.ZodNumber>;
        steps: z.ZodArray<z.ZodNumber>;
        title: z.ZodString;
        detail: z.ZodString;
    }, z.core.$strip>>;
    findingCount: z.ZodNumber;
    wire: z.ZodObject<{
        version: z.ZodLiteral<1>;
        sessionId: z.ZodString;
        seq: z.ZodNumber;
        updatedAt: z.ZodNumber;
        totals: z.ZodObject<{
            calls: z.ZodNumber;
            reported: z.ZodNumber;
            exactTotals: z.ZodNumber;
            tokens: z.ZodNumber;
            input: z.ZodNumber;
            output: z.ZodNumber;
            cacheRead: z.ZodNumber;
            cacheWrite: z.ZodNumber;
            reasoning: z.ZodNumber;
            reasoningReports: z.ZodNumber;
            modelMs: z.ZodNumber;
            timedCalls: z.ZodNumber;
            firstMs: z.ZodNumber;
            firstSamples: z.ZodNumber;
            reasoningMs: z.ZodNumber;
            tools: z.ZodNumber;
            toolErrors: z.ZodNumber;
            toolMs: z.ZodNumber;
            bashMs: z.ZodOptional<z.ZodNumber>;
            retries: z.ZodNumber;
        }, z.core.$strip>;
        models: z.ZodArray<z.ZodObject<{
            calls: z.ZodNumber;
            reported: z.ZodNumber;
            exactTotals: z.ZodNumber;
            tokens: z.ZodNumber;
            input: z.ZodNumber;
            output: z.ZodNumber;
            cacheRead: z.ZodNumber;
            cacheWrite: z.ZodNumber;
            reasoning: z.ZodNumber;
            reasoningReports: z.ZodNumber;
            modelMs: z.ZodNumber;
            timedCalls: z.ZodNumber;
            firstMs: z.ZodNumber;
            firstSamples: z.ZodNumber;
            reasoningMs: z.ZodNumber;
            tools: z.ZodNumber;
            toolErrors: z.ZodNumber;
            toolMs: z.ZodNumber;
            bashMs: z.ZodOptional<z.ZodNumber>;
            retries: z.ZodNumber;
            provider: z.ZodString;
            model: z.ZodString;
            effort: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>;
        turn: z.ZodNullable<z.ZodObject<{
            number: z.ZodNumber;
            startedAt: z.ZodNumber;
            endedAt: z.ZodNullable<z.ZodNumber>;
            steps: z.ZodNumber;
            stats: z.ZodObject<{
                calls: z.ZodNumber;
                reported: z.ZodNumber;
                exactTotals: z.ZodNumber;
                tokens: z.ZodNumber;
                input: z.ZodNumber;
                output: z.ZodNumber;
                cacheRead: z.ZodNumber;
                cacheWrite: z.ZodNumber;
                reasoning: z.ZodNumber;
                reasoningReports: z.ZodNumber;
                modelMs: z.ZodNumber;
                timedCalls: z.ZodNumber;
                firstMs: z.ZodNumber;
                firstSamples: z.ZodNumber;
                reasoningMs: z.ZodNumber;
                tools: z.ZodNumber;
                toolErrors: z.ZodNumber;
                toolMs: z.ZodNumber;
                bashMs: z.ZodOptional<z.ZodNumber>;
                retries: z.ZodNumber;
            }, z.core.$strip>;
            route: z.ZodOptional<z.ZodObject<{
                provider: z.ZodString;
                model: z.ZodString;
                effort: z.ZodOptional<z.ZodNullable<z.ZodString>>;
            }, z.core.$strip>>;
        }, z.core.$strip>>;
        pending: z.ZodNullable<z.ZodObject<{
            turn: z.ZodNumber;
            step: z.ZodNumber;
            start: z.ZodNullable<z.ZodNumber>;
            reasoningFirst: z.ZodNullable<z.ZodNumber>;
            reasoningLast: z.ZodNullable<z.ZodNumber>;
            lastContentAt: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>;
        findings: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            kind: z.ZodString;
            turn: z.ZodNumber;
            seqs: z.ZodArray<z.ZodNumber>;
            steps: z.ZodArray<z.ZodNumber>;
            title: z.ZodString;
            detail: z.ZodString;
        }, z.core.$strip>>;
        findingCount: z.ZodNumber;
    }, z.core.$strip>;
}, z.core.$strip>;
export type InsightsView = z.infer<typeof viewSchema>;
type InsightsState = z.infer<typeof stateSchema>;
declare module '@deepseek-ai/dsh-session-projection/types' {
    interface SessionProjectionStateMap {
        watcherInsights: InsightsState;
    }
    interface SessionProjectionMap {
        watcherInsights: InsightsView;
    }
}
export declare function installProjection(ctx: Context): void;
export {};
//# sourceMappingURL=projection.d.ts.map